[selection]
save_to_clipboard = true

[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.normal]
black = "#161821"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "#161821"
foreground = "#d2d4de"

[env]
LANG = "ja_JP.UTF-8"
LC_CTYPE = "ja_JP.UTF-8"
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "PlemolJP Console NF"
style = "Bold"

[font.italic]
family = "PlemolJP Console NF"
style = "Italic"

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/zsh"
